name: OpenOrcaLocal
task: text_generation
url: http://localhost:8080
model: none
pretrained_tokenizer: models/Open-Hermes-2.5
token: DUMMY
timeout: null
headers:
  Content-Type: application/json
cookies: null
stream: True
stream_chunk_size: 5
params:
  stop_sequences: #Used only for text processing and does not affect text generation.
  - <|im_end|>
  - <|im_start|>
  max_length: 4096
  temperature: 0.3
  stream: ${..stream}