name: OpenOrcaLocal
task: text_generation
model: http://localhost:8080
pretrained_tokenizer: models/Qwen1.5-14B-Chat-AWQ
token: DUMMY
timeout: null
headers:
  Content-Type: application/json
cookies: null
stream: True
stream_chunk_size: 5
params:
  stop_sequences: #Used only for text processing and does not affect text generation.
  - <|im_end|>
  - <|im_start|>
  max_length: 4096
  temperature: 0.3
  stream: ${..stream}