api:
  cors_urls: 
   - https://app.yakwith.ai
   - https://dev.d2civivj65v1p0.amplifyapp.com
  port: 8884  # Port that fastAPI runs on

# Credentials stored in .env
database:
  url: localhost:27017
  name: yak_test_db # mongodb database
  default_collection: cafes
  services_collection: services # Collection of miscellaneous tables (e.g for populating defaults)
  data_collection: data # Collection containing miscellaneous data e.g. for populating dropdown, avatar configurations, model configs.

assets:
  image_folder: /home/mtman/Repos/yakwith.ai/voice_chat/Images   #Ensure this matches the folder mapped to the mongodb volume in .env
  model_folder: /home/mtman/Repos/yakwith.ai/models   #Ensure this matches the folder mapped to the mongodb volume in .env
  thumbnail_image_width: 400 # pixel height of thumbnail used for displaying in menu gallery.
  max_camera_resolution: 2048

logging: 
  root_folder: /home/mtman/Documents/Repos/yakwith.ai/voice_chat/logs
  metric_logs_folder: /home/mtman/Documents/Repos/yakwith.ai/voice_chat/logs/metrics

ocr:
  url: http://localhost:8885/tesseract # Must ensure this matches the port specified in the environment variables used by docker-compose.

text_to_speech:
  default_voice_id: en-AU-KimNeural   # for Azure TextToSpeech

nlp:
  max_length_of_prompt_buffer: 2 # The number of prompt fragments that, when reached, should be sent to the LLM. 